# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: currency_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='currency_service.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x16\x63urrency_service.proto\"Q\n\x0f\x43urrencyRequest\x12\x1f\n\x0c\x63urrencyFrom\x18\x01 \x02(\x0e\x32\t.Currency\x12\x1d\n\ncurrencyTo\x18\x02 \x02(\x0e\x32\t.Currency\"\x15\n\x04Rate\x12\r\n\x05value\x18\x02 \x02(\x01*.\n\x08\x43urrency\x12\x07\n\x03PLN\x10\x00\x12\x07\n\x03\x45UR\x10\x01\x12\x07\n\x03USD\x10\x02\x12\x07\n\x03\x43HF\x10\x03\x32\x41\n\x0f\x43urrencyService\x12.\n\x0fGetCurrencyRate\x12\x10.CurrencyRequest\x1a\x05.Rate\"\x00\x30\x01\x42&\n$pl.edu.agh.wiet.sr.banking.generated')
)

_CURRENCY = _descriptor.EnumDescriptor(
  name='Currency',
  full_name='Currency',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PLN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EUR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USD', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHF', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=132,
  serialized_end=178,
)
_sym_db.RegisterEnumDescriptor(_CURRENCY)

Currency = enum_type_wrapper.EnumTypeWrapper(_CURRENCY)
PLN = 0
EUR = 1
USD = 2
CHF = 3



_CURRENCYREQUEST = _descriptor.Descriptor(
  name='CurrencyRequest',
  full_name='CurrencyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='currencyFrom', full_name='CurrencyRequest.currencyFrom', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currencyTo', full_name='CurrencyRequest.currencyTo', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=107,
)


_RATE = _descriptor.Descriptor(
  name='Rate',
  full_name='Rate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Rate.value', index=0,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=130,
)

_CURRENCYREQUEST.fields_by_name['currencyFrom'].enum_type = _CURRENCY
_CURRENCYREQUEST.fields_by_name['currencyTo'].enum_type = _CURRENCY
DESCRIPTOR.message_types_by_name['CurrencyRequest'] = _CURRENCYREQUEST
DESCRIPTOR.message_types_by_name['Rate'] = _RATE
DESCRIPTOR.enum_types_by_name['Currency'] = _CURRENCY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CurrencyRequest = _reflection.GeneratedProtocolMessageType('CurrencyRequest', (_message.Message,), dict(
  DESCRIPTOR = _CURRENCYREQUEST,
  __module__ = 'currency_service_pb2'
  # @@protoc_insertion_point(class_scope:CurrencyRequest)
  ))
_sym_db.RegisterMessage(CurrencyRequest)

Rate = _reflection.GeneratedProtocolMessageType('Rate', (_message.Message,), dict(
  DESCRIPTOR = _RATE,
  __module__ = 'currency_service_pb2'
  # @@protoc_insertion_point(class_scope:Rate)
  ))
_sym_db.RegisterMessage(Rate)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$pl.edu.agh.wiet.sr.banking.generated'))

_CURRENCYSERVICE = _descriptor.ServiceDescriptor(
  name='CurrencyService',
  full_name='CurrencyService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=180,
  serialized_end=245,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCurrencyRate',
    full_name='CurrencyService.GetCurrencyRate',
    index=0,
    containing_service=None,
    input_type=_CURRENCYREQUEST,
    output_type=_RATE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CURRENCYSERVICE)

DESCRIPTOR.services_by_name['CurrencyService'] = _CURRENCYSERVICE

# @@protoc_insertion_point(module_scope)
