# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import currency_service_pb2 as currency__service__pb2


class CurrencyServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetCurrencyRate = channel.unary_stream(
        '/CurrencyService/GetCurrencyRate',
        request_serializer=currency__service__pb2.CurrencyRequest.SerializeToString,
        response_deserializer=currency__service__pb2.Rate.FromString,
        )


class CurrencyServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetCurrencyRate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CurrencyServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetCurrencyRate': grpc.unary_stream_rpc_method_handler(
          servicer.GetCurrencyRate,
          request_deserializer=currency__service__pb2.CurrencyRequest.FromString,
          response_serializer=currency__service__pb2.Rate.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CurrencyService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
